### ISSUE TITLE
using not case-sensitive symbols?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ThomasWaldmann/py-esp32-ulp#10]
Usually I am all for case-sensitivity, because it avoids a lot of issues.

But considering the symbol names from espressif have a lot of SYMBOLS_LIKE_THAT, I find that rather ugly, so I am considering just ignoring case, so typing the same stuff in lowercase does also match.

Opinions?

**Comment by igrr** [comment]
Do you mean symbols in the "symbols in object file" sense or as in identifiers? If we have upper case symbols in object files somewhere, that's likely a but which we should fix. If this is about assembly tokens, then not making them case sensitive makes sense, as this is how binutils works as well. FWIW, [ULP examples](https://github.com/espressif/esp-idf/blob/master/examples/system/ulp/main/ulp/pulse_cnt.S) use lower case, except for preprocessor macros.

**Comment by ThomasWaldmann** [comment]
I meant stuff in assembly source. Instructions and also long-named constants for specific SoC register addresses / memory areas. The latter is somehow convention to be uppercase, but still, typing / reading uppercase is not nice.

I had mostly looked at `ulp.h` at the time I wrote that. I am using the tech ref and other non-deprecated docs now.

Yes, that example already looks much better.

**Comment by ThomasWaldmann** [comment]
ok, so does that look ok?:

- mnemonics: ulp instructions: not case-sensitive
- mnemonics: assembler directives: not case-sensitive
- operands: registers: not case-sensitive
- operands: conditions (eq, ov, ge, ...): not case-sensitive
- labels / symbols: case-sensitive

**Comment by igrr** [comment]
Yes, this looks reasonable!

**Comment by ThomasWaldmann** [comment]
guess this is how it is currently implemented, closing.
