### ISSUE TITLE
clarify "not implemented"-like comments in ulp.h

### ISSUE THREAD

**Issue by ThomasWaldmann** [ThomasWaldmann/py-esp32-ulp#9]
there are some such comments in espressif's `ulp.h` and while they say "not implemented", at least some of them have code in that file.

does it mean the functionality is not implemented in the hardware (ULP coprocessor) yet?

or is it just some leftover that is outdated and should be removed?

**Comment by ThomasWaldmann** [comment]
https://github.com/espressif/esp-idf/blob/master/components/ulp/include/esp32/ulp.h#L46

there and some other places.

**Comment by igrr** [comment]
Mostly leftovers, yes, related to corresponding instruction macros missing. All instructions which are mentioned in the TRM are supported by the hardware.

**Comment by ThomasWaldmann** [comment]
OK, thanks for clarifying.
